"""empty message

Revision ID: 2474dfde2124
Revises: 61c7dd8569a1
Create Date: 2020-10-27 11:31:13.734231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2474dfde2124'
down_revision = '61c7dd8569a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('sum_to_live', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'sum_to_live')
    # ### end Alembic commands ###
