"""empty message

Revision ID: 3c60c764fbe0
Revises: e761b3e62162
Create Date: 2020-10-30 16:47:31.316341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c60c764fbe0'
down_revision = 'e761b3e62162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_db', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_db', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
