"""empty message

Revision ID: 440b3339ae7d
Revises: 7d5270fc80dc
Create Date: 2020-10-28 17:25:11.991199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440b3339ae7d'
down_revision = '7d5270fc80dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_expenses_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('to_pay', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_expenses_db')
    # ### end Alembic commands ###
