"""empty message

Revision ID: 4b3510a88c5b
Revises: 3c60c764fbe0
Create Date: 2020-11-05 16:12:19.155889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3510a88c5b'
down_revision = '3c60c764fbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history_db', sa.Column('savings_to_pay', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('history_db', sa.Column('savings_value', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history_db', 'savings_value')
    op.drop_column('history_db', 'savings_to_pay')
    # ### end Alembic commands ###
