"""empty message

Revision ID: 61c7dd8569a1
Revises: 7a9b16dd882f
Create Date: 2020-10-26 19:51:16.680984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c7dd8569a1'
down_revision = '7a9b16dd882f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_db', sa.Column('percent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_db', 'percent')
    # ### end Alembic commands ###
