"""empty message

Revision ID: 7ef354e17a31
Revises: 07a486d56e9e
Create Date: 2020-10-28 19:45:09.212365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef354e17a31'
down_revision = '07a486d56e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'sum_to_live')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('sum_to_live', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
