"""empty message

Revision ID: e748a477e9ba
Revises: 7ef354e17a31
Create Date: 2020-10-29 17:34:07.241043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e748a477e9ba'
down_revision = '7ef354e17a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_db', 'sum_to_live')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_db', sa.Column('sum_to_live', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
